### ISSUE TITLE
change order of filter navigation layer

### ISSUE THREAD

**Issue by jburkhardt** [tzyganu/stock-filter#10]
Thanks for the extension! It works fine out of the box!  

I wonder if it is possible to change the order of the filter in the navigation layer. Per default the in-stock filter is on the bottom/last filter option. I would like to place the filter further up.  

Can you give an advice how to reorder the filters?  

Usually one can change the order of the attributes in `admin > catalog > attributes > manage attributes`. However there is no attribute associated with the in-stock filter.

Andy help is appreciated!
Regards,
Johannes

**Comment by tzyganu** [comment]
@jburkhardt I've created this a long time ago, but if I remember correctly, I actually tried to make the position of the block configurable, but couldn't for some reason.  
But if you want to give it a go, you can play with the order of the filters by changing [the lines under this one](https://github.com/tzyganu/stock-filter/blob/master/app/code/community/Easylife/StockFilter/Model/Observer.php#L113)

**Comment by jburkhardt** [comment]
@tzyganu Thanks for the update. If I figure something out, I will let you know.

**Comment by Ginkosama** [comment]
To have it in first position, just change [that line](https://github.com/tzyganu/stock-filter/blob/master/app/code/community/Easylife/StockFilter/Model/Observer.php#L115) from :

$filters[] = $filterBlock;

to :

array_unshift($filters, $filterBlock);

**Comment by jburkhardt** [comment]
@Ginkosama Thanks! Works fine - perfect!
