### ISSUE TITLE
stock filter only for specified categories

### ISSUE THREAD

**Issue by jburkhardt** [tzyganu/stock-filter#11]
Hi,

does anyone know how to display the stock filter only for certain categories?

At the current version the stock filter displays on all category pages/filters. The idea is to use the category IDs as a specification and restrict the stock filter only to those categories. 

Any help is appreciated!

Maybe @tzyganu or @Ginkosama have any idea?

Thanks,
Johannes

**Comment by Ginkosama** [comment]
You will have to proceed in two step to add it, first in the admin part to select which categories are enabled for the filter (either in the categories tabs a check box, either in the system config with a multi select list), then edit the front part of the module to check if the current category is enabled for the filter or not, the best would be directly when it check if the module (as a whole) is enable or not.

**Comment by jburkhardt** [comment]
@Ginkosama Thanks for the instruction! This approach sounds convenient and seems to be a complete and clean implementation of the feature. However I don´t know how to develop this on short notice. Maybe we could make a feature request? You are welcome to help me on that!

In the meanwhile, is there a workaround solution with a hard coded if condition (if category Id == 4, then display filter) in the module or anything alike?

**Comment by Ginkosama** [comment]
Yes you should make a feature request if you can't code it yourself, as i don't have much time on my hands to help you with that.

If you want an hard coded version you can try ( i didn't tried it ) to change [that line](https://github.com/tzyganu/stock-filter/blob/master/app/code/community/Easylife/StockFilter/Helper/Data.php#L53) from :

if (!$this->isEnabled()) {

to :

if (!$this->isEnabled() || !in_array(Mage::registry('current_category')->getId(), array(2, 4, 6, 8))) {

And it should activate the stock filter only on the categories ID 2,4,6 and 8

**Comment by jburkhardt** [comment]
This works fine!
@Ginkosama Thank you!

**Comment by jburkhardt** [comment]
@Ginkosama The stock filter now works on the specified categories only. However the whole search in the magento store does not work any more due to the change. Do have any idea what is going wrong here or why the search gets corrupted?  
**Update:**
`Mage::registry('current_category')->getId()` returns NULL on non category pages. Hence some pages like the search might crash.  
**Solution:**  
`Mage::getModel('catalog/layer')->getCurrentCategory()->getId()` works on category pages and does not interfere with the search.
