### ISSUE TITLE
Do we need to create an attribute?

### ISSUE THREAD

**Issue by nmohanan** [tzyganu/stock-filter#5]
Hi, i have installed this extension and it is not appearing in the layered navigation, do i need to create an attribute and make that attribute searchable (Used for Sorting in Product Listing->yes). ? I am using custom theme.

**Comment by tzyganu** [comment]
@nmohanan You don't need to create any attributes. It should work out of the box. Just make sure you have "Display out of stock products" set to "Yes". [Read this for more details](https://github.com/tzyganu/stock-filter#configuration)

**Comment by tzyganu** [comment]
Closed due to inactivity.
