### ISSUE TITLE
Filter Not showing

### ISSUE THREAD

**Issue by jalpaambab** [tzyganu/stock-filter#6]
Hi,  
I have installed this extension and it is not appearing in the layered navigation.

I have also integrated manadev layered navigation filter, this plugin is not working with manadev while it seems to be working with fresh magento.

Can you please help me to solve the same.

**Comment by tzyganu** [comment]
@jalpaambab  Yep. It does not work with other extensions that affect the layered navigation. 
Sorry, but I will not start to make it compatible with all the extensions that exist on the market regarding the layered nav.
