### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by soncp** [tzyganu/stock-filter#7]
Hello, 
I have got an message, 
a:5:{i:0;s:824:"SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'stock_status' in order clause is ambiguous, query was: SELECT DISTINCT `e`.`attribute_set_id` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id = '13'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 LEFT JOIN `cataloginventory_stock_status` AS `cisi` ON (cisi.product_id=e.entity_id) AND (cisi.website_id = '1')
 LEFT JOIN `cataloginventory_stock_status` AS `stock_status` ON e.entity_id = stock_status.product_id AND stock_status.website_id=1 ORDER BY `stock_status` desc";i:1;s:3915:"#0 /home/pt/aht2931/src/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/pt/aht2931/src/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/pt/aht2931/src/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/pt/aht2931/src/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT DISTINCT...', Array)...

How can i fixe it?

**Comment by tzyganu** [comment]
@soncp  what magento version are you using? Also, does this happen on a product list page or a custom page?

**Comment by tzyganu** [comment]
Closed due to inactivity
