### ISSUE TITLE
Extension is not showing on frontend?

### ISSUE THREAD

**Issue by kirmal-ghrix** [tzyganu/stock-filter#8]
I have to installed stock filter plugin. But its not showing on frontend.

**Comment by tzyganu** [comment]
@kirmaljeetkaur Do you have the out of stock products visible on your website?

**Comment by kirmal-ghrix** [comment]
Thanks for reply Marius , its working now.

On Mon, Apr 4, 2016 at 4:17 PM, Marius Strajeru notifications@github.com
wrote:

> @kirmaljeetkaur https://github.com/kirmaljeetkaur Do you have the out
> of stock products visible on your website?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/tzyganu/stock-filter/issues/8#issuecomment-205238173

## 

kimmi brar
