### ISSUE TITLE
check for qty

### ISSUE THREAD

**Issue by akkermanronald** [tzyganu/stock-filter#9]
Hi,
We have a lot of products for which backorders are allowed. For these products the setting "is_in_stock" also needs to be 1 (in stock). We therefore like to filter products with qty > 1 instead of "is_in_stock" so customers see the products that we actually have in stock first. Any suggestions? 
Regards
Ronald

**Comment by tzyganu** [comment]
@akkermanronald I don't know how you can do that and it is not in the scope of this extension.
